[default_view]

keymap = [
  { keys = ["f"], command = ":shell touch " },
  { keys = ["escape"], command = "escape" },
  { keys = ["ctrl+g"], command = "new_tab" },
  { keys = ["alt+g"], command = "new_tab --cursor" },
  { keys = ["G"], command = "new_tab --current" },
  { keys = ["W"], command = "close_tab" },
  { keys = ["ctrl+w"], command = "close_tab" },
  { keys = ["q"], command = "close_tab" },
  { keys = ["ctrl+c"], command = "quit" },
  { keys = ["Q"], command = "quit --output-current-directory" },

  { keys = ["P"], command = "reload_dirlist" },
  { keys = ["z", "h"], command = "toggle_hidden" },
  { keys = ["ctrl+h"], command = "toggle_hidden" },
  { keys = ["\t"], command = "tab_switch 1" },
  { keys = ["backtab"], command = "tab_switch -1" },

  { keys = ["alt+1"], command = "tab_switch_index 1" },
  { keys = ["alt+2"], command = "tab_switch_index 2" },
  { keys = ["alt+3"], command = "tab_switch_index 3" },
  { keys = ["alt+4"], command = "tab_switch_index 4" },
  { keys = ["alt+5"], command = "tab_switch_index 5" },

  { keys = ["1"], command = "numbered_command 1" },
  { keys = ["2"], command = "numbered_command 2" },
  { keys = ["3"], command = "numbered_command 3" },
  { keys = ["4"], command = "numbered_command 4" },
  { keys = ["5"], command = "numbered_command 5" },
  { keys = ["6"], command = "numbered_command 6" },
  { keys = ["7"], command = "numbered_command 7" },
  { keys = ["8"], command = "numbered_command 8" },
  { keys = ["9"], command = "numbered_command 9" },

  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["arrow_left"], command = "cd .." },
  { keys = ["arrow_right"], command = "open" },
  { keys = ["\n"], command = "open" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },
  { keys = ["page_up"], command = "cursor_move_page_up" },
  { keys = ["page_down"], command = "cursor_move_page_down" },
  { keys = ["ctrl+l"], command = "cursor_move_page_up 0.5" },
  { keys = ["ctrl+s"], command = "cursor_move_page_down 0.5" },

  # vim-like keybindings
  { keys = ["n"], command = "cursor_move_down" },
  { keys = ["e"], command = "cursor_move_up" },
  { keys = ["h"], command = "cd .." },
  { keys = ["i"], command = "open" },
  { keys = ["d", "d"], command = "cursor_move_home" },
  { keys = ["D"], command = "cursor_move_end" },
  { keys = ["p"], command = "open_with" },

  { keys = ["H"], command = "cursor_move_page_home" },
  { keys = ["I"], command = "cursor_move_page_middle" },
  { keys = ["M"], command = "cursor_move_page_end" },

  { keys = ["["], command = "parent_cursor_move_up" },
  { keys = ["]"], command = "parent_cursor_move_down" },

  { keys = ["c", "s"], command = ":cd " },
  { keys = ["s", "s"], command = "cut_files" },
  { keys = ["j", "j"], command = "copy_files" },
  { keys = ["j", "k"], command = "copy_filename" },
  { keys = ["j", "."], command = "copy_filename_without_extension" },
  { keys = ["j", ";"], command = "copy_filepath" },
  { keys = ["j", "s"], command = "copy_dirpath" },

  { keys = [";", "i"], command = "symlink_files --relative=false" },
  { keys = [";", "I"], command = "symlink_files --relative=true" },

  { keys = ["delete"], command = "delete_files" },
  { keys = ["s", "S"], command = "delete_files" },

  { keys = [";", ";"], command = "paste_files" },
  { keys = [";", "y"], command = "paste_files --overwrite=true" },

  { keys = ["a"], command = "rename_append" },
  { keys = ["A"], command = "rename_prepend" },

  { keys = ["t", "g"], command = ":touch " },

  { keys = [" "], command = "select --toggle=true" },
  { keys = ["g"], command = "select --all=true --toggle=true" },
  { keys = ["V"], command = "toggle_visual" },

  { keys = ["w"], command = "show_tasks --exit-key=w" },
  { keys = ["b", "b"], command = "bulk_rename" },
  { keys = ["="], command = "set_mode" },

  { keys = ["O"], command = ":" },
  { keys = ["o"], command = ":" },

  { keys = ["'"], command = ":shell " },
  { keys = ["m", "e"], command = ":mkdir " },
  { keys = ["c", "w"], command = ":rename " },

  { keys = ["/"], command = ":search " },
  { keys = ["|"], command = ":search_inc " },
  { keys = ["\\"], command = ":search_glob " },
  { keys = ["R"], command = "search_fzf" },
  { keys = ["C"], command = "subdir_fzf" },

  { keys = ["k"], command = "search_next" },
  { keys = ["K"], command = "search_prev" },

  { keys = ["r", "p"], command = "sort reverse" },
  { keys = ["r", "i"], command = "sort lexical" },
  { keys = ["r", "m"], command = "sort mtime" },
  { keys = ["r", "k"], command = "sort natural" },
  { keys = ["r", "r"], command = "sort size" },
  { keys = ["r", "f"], command = "sort ext" },

  { keys = ["m", "r"], command = "linemode size" },
  { keys = ["m", "m"], command = "linemode mtime" },
  { keys = ["m", "M"], command = "linemode sizemtime" },

  { keys = ["d", "p"], command = "cd /" },
  { keys = ["d", "c"], command = "cd ~/.config" },
  { keys = ["d", "s"], command = "cd ~/Downloads" },
  { keys = ["d", "f"], command = "cd /etc" },
  { keys = ["d", "h"], command = "cd ~/" },
  { keys = ["?"], command = "help" },
]

[task_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["n"], command = "cursor_move_down" },
  { keys = ["e"], command = "cursor_move_up" },
  { keys = ["d", "d"], command = "cursor_move_home" },
  { keys = ["D"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]

[help_view]

keymap = [
  # arrow keys
  { keys = ["arrow_up"], command = "cursor_move_up" },
  { keys = ["arrow_down"], command = "cursor_move_down" },
  { keys = ["home"], command = "cursor_move_home" },
  { keys = ["end"], command = "cursor_move_end" },

  # vim-like keybindings
  { keys = ["n"], command = "cursor_move_down" },
  { keys = ["e"], command = "cursor_move_up" },
  { keys = ["d", "d"], command = "cursor_move_home" },
  { keys = ["D"], command = "cursor_move_end" },

  { keys = ["w"], command = "show_tasks" },
  { keys = ["escape"], command = "show_tasks" },
]
