git:
    parseEmoji: true
gui:
    authorColors:
        '*': blue
        CrackTC: '#8fbcbb'
    nerdFontsVersion: '3'
    showBottomLine: false
    theme:
        activeBorderColor:
            - blue
            - bold
        inactiveBorderColor:
            - '#4c566a'
        selectedLineBgColor:
            - black
        selectedRangeBgColor:
            - black
keybinding:
    files:
        stashAllChanges: r
        viewStashOptions: R
    universal:
        confirm: <enter>
        createPatchOptionsMenu: o
        edit: f
        executeShellCommand: <c-p>
        goInto: <enter>
        gotoBottom: D
        gotoTop: d
        jumpToBlock:
            - 1
            - 2
            - 3
            - 4
            - 5
        new: k
        nextBlock: <right>
        nextBlock-alt: N
        nextItem: <down>
        nextItem-alt: n
        nextMatch: k
        nextPage: .
        nextScreenMode: <c-y>
        nextTab: I
        openFile: y
        openRecentRepos: <c-r>
        optionMenu-alt1: '?'
        prevBlock: <left>
        prevBlock-alt: E
        prevItem: <up>
        prevItem-alt: e
        prevMatch: K
        prevPage: ','
        prevTab: H
        pullFiles: ;
        pushFiles: ':'
        quit: q
        quit-alt1: <c-c>
        quitWithoutChangingDirectory: Q
        redo: <c-r>
        refresh: P
        remove: s
        return: <esc>
        scrollDownMain: <pgdown>
        scrollDownMain-alt1: <c-n>
        scrollLeft: h
        scrollRight: i
        scrollUpMain: <pgup>
        scrollUpMain-alt1: <c-e>
        select: <space>
        togglePanel: <tab>
        undo: l
notARepository: quit
os:
    edit: kitty -- nvim -- {{filename}}
    editAtLine: kitty -- nvim +{{line}} -- {{filename}}
    editAtLineAndWait: kitty -- nvim +{{line}} -- {{filename}}
    openDirInEditor: kitty -- nvim -- {{dir}}
promptToReturnFromSubprocess: false
update:
    method: never
