{
  imports = [
    ./anki.nix
    ./asciinema.nix
    ./baidunetdisk.nix
    ./bat.nix
    ./bc.nix
    ./bsdiff.nix
    ./btop.nix
    ./clash.nix
    ./duf.nix
    ./fastfetch.nix
    ./follow.nix
    ./imhex.nix
    ./joshuto
    ./jq.nix
    ./lazygit.nix
    ./llama.nix
    ./localsend.nix
    ./pandoc.nix
    ./proxychains.nix
    ./qbittorrent.nix
    ./ripdrag.nix
    ./rofi
    ./sing-box.nix
    ./tex.nix
    ./video2gif.nix
    ./waydroid.nix
    ./yazi
    ./zip.nix
  ];
}
