{
  imports = [
    ./asciinema.nix
    ./baidunetdisk.nix
    ./bat.nix
    ./bc.nix
    ./bsdiff.nix
    ./clash.nix
    ./fastfetch.nix
    ./joshuto
    ./jq.nix
    ./lazygit
    ./llama.nix
    ./pandoc.nix
    ./proxychains.nix
    ./qbittorrent.nix
    ./ripdrag.nix
    ./rofi
    ./tex.nix
    ./video2gif.nix
    ./yazi
    ./zip.nix
  ];
}
