{
  imports = [
    ./asciinema.nix
    ./baidunetdisk.nix
    ./bc.nix
    ./bsdiff.nix
    ./clash.nix
    ./fastfetch.nix
    ./jq.nix
    ./lazygit.nix
    ./llama.nix
    ./proxychains.nix
    ./qbittorrent.nix
    ./rofi
    ./tex.nix
    ./video2gif.nix
    ./zip.nix
  ];
}
